const APP_VERSION='0.6.0-dev';
const CONTENT_VERSION='math-core-loop-2026-08-31-v3';
const EVENT_SCHEMA_VERSION='2.0';
const KEY='KLH_PUBLIC_WEB_DEV_V06_TESTER';
const LEGACY_KEYS=['KLH_PUBLIC_WEB_DEV_V05_TESTER','KLH_PUBLIC_WEB_DEV_V04_TESTER','KLH_PUBLIC_WEB_DEV_V03_TESTER'];

const SKILLS=[
  {
    id:'division', title:'การหารด้วยตัวหาร 2 หลัก',
    lesson:'ประมาณคำตอบก่อน แล้วใช้การคูณกลับตรวจ เช่น 3,600 ÷ 24 = 150 เพราะ 24 × 150 = 3,600',
    visual:'24 × 150 = 3,600 ⇄ 3,600 ÷ 24 = 150',
    url:'https://proj14.ipst.ac.th/p4/p4-math-book1/math-p4b1-031/',
    diagnostic:{id:'DEV_MATH_DIV_DIAG_001',p:'1,440 ÷ 24 = ?',c:['50','60','70','80'],a:1,wrong:{0:['calculation','คำนวณคลาดเคลื่อน','ลองคูณคำตอบกลับด้วย 24'],2:['estimation','ประเมินขนาดคำตอบสูงไป','24 × 60 = 1,440 พอดี'],3:['estimation','ประเมินขนาดคำตอบสูงไป','ลองเทียบ 24 × 80 กับ 1,440']}},
    fresh:[{id:'DEV_MATH_DIV_001',p:'2,880 ÷ 24 = ?',c:['100','110','120','140'],a:2},{id:'DEV_MATH_DIV_002',p:'4,320 ÷ 27 = ?',c:['120','140','160','180'],a:2},{id:'DEV_MATH_DIV_003',p:'5,250 ÷ 25 = ?',c:['180','200','210','225'],a:2}],
    rescue:{id:'DEV_MATH_DIV_RESCUE_001',p:'3,360 ÷ 24 = ?',c:['120','130','140','150'],a:2,hints:['เริ่มจากประมาณ 3,360 ÷ 24 ว่าควรอยู่แถว 100 กว่า','ลองคูณกลับ: 24 × 140 = 3,360']},
    retest:{id:'DEV_MATH_DIV_POST_001',p:'4,080 ÷ 24 = ?',c:['150','160','170','180'],a:2},
    deep:{prereq:{id:'DEV_MATH_DIV_PRE_001',p:'24 × 14 = ?',c:['240','280','336','360'],a:2},lesson:'ถ้าหารยาวแล้วหลงทาง ให้กลับมาใช้ “ก้อนคูณ” ก่อน เช่น 4,080 ÷ 24: 24×100=2,400 เหลือ 1,680 และ 24×70=1,680 ดังนั้นรวมเป็น 170',visual:'24×100 + 24×70 = 4,080 → 4,080÷24 = 170',transfer:{id:'DEV_MATH_DIV_DEEP_001',p:'3,840 ÷ 24 = ?',c:['140','150','160','180'],a:2}},
    retention:[{day:1,id:'DEV_MATH_DIV_RET_D1',p:'2,640 ÷ 24 = ?',c:['100','110','120','130'],a:1},{day:3,id:'DEV_MATH_DIV_RET_D3',p:'3,780 ÷ 27 = ?',c:['120','130','140','150'],a:2},{day:7,id:'DEV_MATH_DIV_RET_D7',p:'4,500 ÷ 25 = ?',c:['160','170','180','190'],a:2},{day:21,id:'DEV_MATH_DIV_RET_D21',p:'5,760 ÷ 24 = ?',c:['220','230','240','250'],a:2}]
  },
  {
    id:'fraction', title:'เศษส่วนของเศษส่วน',
    lesson:'คำว่า “ของ” ให้คิดเป็นการคูณ เช่น 1/4 ของ 3/5 = 1/4 × 3/5',
    visual:'1/4 ของ 3/5 = 3/20',
    url:'https://proj14.ipst.ac.th/p5/p5-math-book1/math-p5b1-014/',
    diagnostic:{id:'DEV_MATH_FRAC_DIAG_001',p:'2/3 ของ 3/4 เท่ากับเท่าไร?',c:['1/4','1/3','1/2','2/3'],a:2,wrong:{0:['procedure','คูณเศษส่วนไม่ครบ','คำว่า “ของ” ให้คูณ 2/3 × 3/4'],1:['concept','อาจสับสนการคูณกับการหาร','คูณเศษกับเศษ และส่วนกับส่วน'],3:['concept','อาจเลือกค่าที่ดูคุ้นโดยไม่คำนวณ','เขียน 2/3 × 3/4 ก่อนตัดทอน']}},
    fresh:[{id:'DEV_MATH_FRAC_001',p:'มีน้ำ 4/5 ถัง ใช้ไป 1/2 ของน้ำที่มี เหลือเท่าไร?',c:['1/5','2/5','3/5','4/5'],a:1},{id:'DEV_MATH_FRAC_002',p:'มีเค้ก 3/4 ก้อน กินไป 1/3 ของที่มี กินไปเท่าไร?',c:['1/4','1/3','1/2','2/3'],a:0},{id:'DEV_MATH_FRAC_003',p:'มีน้ำ 5/6 ถัง ใช้ไป 2/5 ของที่มี เหลือเท่าไร?',c:['1/3','1/2','3/5','2/3'],a:1}],
    rescue:{id:'DEV_MATH_FRAC_RESCUE_001',p:'มีน้ำ 3/4 ถัง ใช้ไป 2/3 ของน้ำที่มี ใช้ไปเท่าไร?',c:['1/3','1/2','2/3','3/4'],a:1,hints:['คำว่า “2/3 ของ 3/4” แปลเป็น 2/3 × 3/4','2/3 × 3/4 = 6/12 แล้วตัดทอน']},
    retest:{id:'DEV_MATH_FRAC_POST_001',p:'4/5 ของ 5/8 เท่ากับเท่าไร?',c:['2/5','1/2','3/5','4/5'],a:1},
    deep:{prereq:{id:'DEV_MATH_FRAC_PRE_001',p:'2/5 × 5/6 เท่ากับเท่าไร?',c:['1/5','1/3','2/5','5/6'],a:1},lesson:'โจทย์ “ใช้ไปเท่าไร” กับ “เหลือเท่าไร” เป็นคนละคำถาม ขั้นแรกหาส่วนที่ใช้ด้วยการคูณก่อน แล้วถ้าถามว่าเหลือจึงเอาปริมาณเดิมลบส่วนที่ใช้',visual:'ปริมาณเดิม → หา “ส่วนที่ใช้” → เดิม − ใช้ = เหลือ',transfer:{id:'DEV_MATH_FRAC_DEEP_001',p:'มีน้ำ 7/8 ถัง ใช้ไป 2/7 ของน้ำที่มี เหลือเท่าไร?',c:['1/4','3/8','1/2','5/8'],a:3}},
    retention:[{day:1,id:'DEV_MATH_FRAC_RET_D1',p:'3/5 ของ 5/9 เท่ากับเท่าไร?',c:['1/3','2/5','3/5','5/9'],a:0},{day:3,id:'DEV_MATH_FRAC_RET_D3',p:'2/7 ของ 7/8 เท่ากับเท่าไร?',c:['1/4','2/7','7/16','1/2'],a:0},{day:7,id:'DEV_MATH_FRAC_RET_D7',p:'มีน้ำ 6/7 ถัง ใช้ไป 1/3 ของที่มี เหลือเท่าไร?',c:['2/7','3/7','4/7','5/7'],a:2},{day:21,id:'DEV_MATH_FRAC_RET_D21',p:'5/6 ของ 3/10 เท่ากับเท่าไร?',c:['1/4','1/3','2/5','1/2'],a:0}]
  },
  {
    id:'decimal', title:'หารทศนิยมด้วยทศนิยม',
    lesson:'ทำตัวหารให้เป็นจำนวนเต็ม โดยเลื่อนจุดทศนิยมของทั้งตัวตั้งและตัวหารเท่ากัน',
    visual:'2.4 ÷ 0.15 → 240 ÷ 15 = 16',
    url:'https://proj14.ipst.ac.th/p6/p6-math-book1/math-p6b1-029/',
    diagnostic:{id:'DEV_MATH_DEC_DIAG_001',p:'2.4 ÷ 0.3 = ?',c:['0.8','8','80','800'],a:1,wrong:{0:['place_value','ตำแหน่งทศนิยมคลาดเคลื่อน','เลื่อนจุดของทั้ง 2.4 และ 0.3 หนึ่งตำแหน่ง'],2:['place_value','คำตอบมากเกินไป 10 เท่า','24 ÷ 3 = 8 ไม่ใช่ 80'],3:['place_value','คำตอบมากเกินไป 100 เท่า','ทำตัวหารเป็นจำนวนเต็มก่อน']}},
    fresh:[{id:'DEV_MATH_DEC_001',p:'1.8 ÷ 0.2 = ?',c:['6','7','8','9'],a:3},{id:'DEV_MATH_DEC_002',p:'3.6 ÷ 0.12 = ?',c:['20','25','30','36'],a:2},{id:'DEV_MATH_DEC_003',p:'4.95 ÷ 0.15 = ?',c:['30','32','33','35'],a:2}],
    rescue:{id:'DEV_MATH_DEC_RESCUE_001',p:'6.4 ÷ 0.16 = ?',c:['4','20','40','400'],a:2,hints:['เลื่อนจุด 2 ตำแหน่งทั้งคู่: 640 ÷ 16','16 × 40 = 640']},
    retest:{id:'DEV_MATH_DEC_POST_001',p:'7.2 ÷ 0.18 = ?',c:['4','20','40','80'],a:2},
    deep:{prereq:{id:'DEV_MATH_DEC_PRE_001',p:'7.2 ÷ 0.18 ถ้าเลื่อนจุด 2 ตำแหน่งทั้งคู่ จะกลายเป็นข้อใด?',c:['72 ÷ 18','720 ÷ 18','720 ÷ 180','7,200 ÷ 18'],a:1},lesson:'กฎสำคัญคือเลื่อนจุด “ทั้งตัวตั้งและตัวหารเท่ากัน” จนตัวหารเป็นจำนวนเต็ม แล้วค่อยหารตามปกติ อย่าเลื่อนข้างเดียว เพราะค่าของโจทย์จะเปลี่ยน',visual:'7.2 ÷ 0.18 → 720 ÷ 18 = 40',transfer:{id:'DEV_MATH_DEC_DEEP_001',p:'5.4 ÷ 0.18 = ?',c:['3','20','30','300'],a:2}},
    retention:[{day:1,id:'DEV_MATH_DEC_RET_D1',p:'4.2 ÷ 0.14 = ?',c:['3','20','30','40'],a:2},{day:3,id:'DEV_MATH_DEC_RET_D3',p:'8.1 ÷ 0.27 = ?',c:['3','27','30','300'],a:2},{day:7,id:'DEV_MATH_DEC_RET_D7',p:'6.3 ÷ 0.21 = ?',c:['3','21','30','300'],a:2},{day:21,id:'DEV_MATH_DEC_RET_D21',p:'9.6 ÷ 0.24 = ?',c:['4','24','40','400'],a:2}]
  }
];

function blank(){return{profile:null,done:{},results:{},skillState:{},attemptHistory:[],retentionHistory:[],events:[]}}
function repairSkillState(ss={}){const x={...ss};if(x.status==='NEEDS_FOUNDATION_REPAIR'){x.retentionEligible=false;x.retentionDue=[];x.nextAction='DEEP_REPAIR'}return x}
function normalize(s){const results={};Object.entries(s?.results||{}).forEach(([skill,r])=>{if(r&&r.freshScore!=null)results[skill]=r;else if(r&&r.score!=null)results[skill]={freshScore:r.score,rescueScore:null,postSupportFreshScore:null,avgConfidence:r.confidence??null,at:r.at||null,label:'MIGRATED_LEGACY_DEV'}});const skillState={};Object.entries(s?.skillState||{}).forEach(([k,v])=>skillState[k]=repairSkillState(v));return{profile:s?.profile||null,done:s?.done||{},results,skillState,attemptHistory:Array.isArray(s?.attemptHistory)?s.attemptHistory:[],retentionHistory:Array.isArray(s?.retentionHistory)?s.retentionHistory:[],events:Array.isArray(s?.events)?s.events:[]}}
function loadState(){try{const now=JSON.parse(localStorage.getItem(KEY)||'null');if(now)return normalize(now)}catch(e){}for(const legacyKey of LEGACY_KEYS){try{const old=JSON.parse(localStorage.getItem(legacyKey)||'null');if(old){const m=normalize(old);m._migratedFrom=legacyKey;localStorage.setItem(KEY,JSON.stringify(m));return m}}catch(e){}}return blank()}
let state=loadState();
let active=null,phase='idle',idx=0,answers=[],conf=[],itemStartAt=0,diagnosticEvidence=null,wrongEvidence=[],rescueHintLevel=0,currentAttemptId=null,attemptStartedAt=null,currentRetentionDay=null,deepPrereqEvidence=null;
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function nowIso(){return new Date().toISOString()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function log(type,extra={}){state.events.push({ts:nowIso(),type,appVersion:APP_VERSION,contentVersion:CONTENT_VERSION,eventSchemaVersion:EVENT_SCHEMA_VERSION,attemptId:currentAttemptId,scenario:state.profile?.scenario||null,tester:state.profile?.tester||null,...extra});save()}
if(state._migratedFrom){const from=state._migratedFrom;delete state._migratedFrom;log('state_migrated',{fromKey:from,toKey:KEY,migration:'v06_repair_retention_eligibility'})}
function hideAll(){['setup','home','learn','telemetry'].forEach(x=>document.getElementById(x).classList.add('hidden'))}
function retentionSchedule(skill){const base=Date.now();return skill.retention.map(q=>({day:q.day,questionId:q.id,dueAt:new Date(base+q.day*86400000).toISOString(),status:'PENDING'}))}
function deriveSkillStatus(freshScore,postSupportFreshScore){if(freshScore===100)return'TENTATIVE_MASTERY_DEV';if(postSupportFreshScore===100)return'TRANSFER_AFTER_SUPPORT_DEV';return'NEEDS_FOUNDATION_REPAIR'}
function userStateText(status){const m={TENTATIVE_MASTERY_DEV:'รอบนี้เข้าใจได้ดี',TRANSFER_AFTER_SUPPORT_DEV:'ดีขึ้นหลังทบทวน และทำโจทย์ใหม่ได้แล้ว',TRANSFER_AFTER_DEEP_REPAIR_DEV:'ซ่อมพื้นฐานแล้ว และกลับมาทำโจทย์ใหม่ได้',RETENTION_CONFIRMED_DEV:'ยังจำและนำไปใช้ได้ดี',RETENTION_WEAK_DEV:'ความรู้เริ่มจาง ควรทบทวนสั้นๆ',NEEDS_FOUNDATION_REPAIR:'ยังมีพื้นฐานบางจุดที่ต้องฝึกเพิ่ม'};return m[status]||'กำลังเก็บหลักฐานเพิ่ม'}
function userStateEmoji(status){return['TENTATIVE_MASTERY_DEV','RETENTION_CONFIRMED_DEV'].includes(status)?'🎯':['TRANSFER_AFTER_SUPPORT_DEV','TRANSFER_AFTER_DEEP_REPAIR_DEV'].includes(status)?'💪':status==='RETENTION_WEAK_DEV'?'🔁':'🧩'}
function diagnosisThai(d){const map={calculation:'คำนวณยังไม่แม่น',estimation:'การกะขนาดคำตอบยังคลาดเคลื่อน',procedure:'ขั้นตอนการทำยังไม่แม่น',concept:'แนวคิดบางจุดยังสับสน',place_value:'ตำแหน่งทศนิยมยังหลอกเราได้',misconception_risk:'อาจมีแนวคิดบางจุดที่เข้าใจคลาดเคลื่อน',strategy_or_processing_gap:'ยังเลือกวิธีทำได้ไม่คล่อง',knowledge_or_prerequisite_gap:'อาจมีพื้นฐานก่อนหน้านี้ที่ต้องเติม',procedural_gap:'ขั้นตอนการทำยังไม่คล่อง',low_confidence_correct:'ทำถูกแล้ว แต่ยังไม่ค่อยมั่นใจ',no_error_observed:'ยังไม่พบจุดติดจากข้อนี้'};return map[d.type]||'มีจุดหนึ่งที่เราน่าลองแกะเพิ่ม'}
function devDetails(html){return `<details class="devdetails"><summary>รายละเอียดสำหรับ DEV</summary><div class="devbox">${html}</div></details>`}
function dueRetentionItems(){const now=Date.now(),out=[];SKILLS.forEach(s=>{const ss=state.skillState[s.id];(ss?.retentionDue||[]).forEach(r=>{if(r.status==='PENDING'&&Date.parse(r.dueAt)<=now)out.push({skill:s,entry:r})})});return out.sort((a,b)=>Date.parse(a.entry.dueAt)-Date.parse(b.entry.dueAt))}
function priorityScore(s){const ss=state.skillState[s.id];if(dueRetentionItems().some(x=>x.skill.id===s.id))return 100;if(ss?.nextAction==='DEEP_REPAIR')return 90;if(ss?.nextAction==='REFRESH_REPAIR')return 85;if(!state.results[s.id])return 70;if(ss?.retentionEligible)return 30;return 50}
function adaptiveRecommendation(){return [...SKILLS].sort((a,b)=>priorityScore(b)-priorityScore(a))[0]}
function enterApp(){state.profile={tester:document.getElementById('tester').value.trim()||'DEV Tester',scenario:document.getElementById('scenario').value};log('session_start');renderHome()}
function renderHome(){hideAll();document.getElementById('home').classList.remove('hidden');document.getElementById('hello').textContent='พร้อมลุยกันต่อไหม?';document.getElementById('scenarioText').textContent='วันนี้เราแข่งกับโจทย์และตัวเราเอง — ไม่แข่งกับใคร';document.getElementById('completedKpi').textContent=Object.keys(state.done).length;document.getElementById('eventKpi').textContent=state.attemptHistory.length+state.retentionHistory.length;document.getElementById('modeKpi').textContent='เรียน → ลอง → ซ่อม → จำ';document.getElementById('versionNote').textContent='App '+APP_VERSION+' • Content '+CONTENT_VERSION+' • Event schema '+EVENT_SCHEMA_VERSION+' • events '+state.events.length;
  const rec=adaptiveRecommendation(),recSS=state.skillState[rec.id],due=dueRetentionItems();
  document.getElementById('adaptivePanel').innerHTML=`<div class="card"><div class="lab">ระบบแนะนำให้ทำต่อ</div><h2>${esc(rec.title)}</h2><p class="muted">${due.some(x=>x.skill.id===rec.id)?'ถึงเวลาทบทวนแล้ว — มาดูกันว่ายังจำได้จริงไหม':recSS?.nextAction==='DEEP_REPAIR'?'หัวข้อนี้ควรซ่อมพื้นฐานก่อน ไม่ต้องฝืนทำโจทย์ยากต่อ':recSS?.nextAction==='REFRESH_REPAIR'?'เคยทำได้แล้วแต่เริ่มจาง ทบทวนสั้นๆ แล้วจะกลับมาไว':'นี่คือภารกิจที่ให้ข้อมูลกับระบบได้คุ้มที่สุดตอนนี้'}</p></div>`;
  document.getElementById('retentionPanel').innerHTML=due.length?`<div class="card"><h2>ถึงเวลาทบทวนความจำ 🧠</h2><p class="muted">เราไม่ได้ถามข้อเดิมซ้ำ แต่ใช้โจทย์ใหม่ดูว่าความรู้ยังอยู่ไหม</p><div class="grid queue">${due.map(x=>`<div class="module"><strong>${esc(x.skill.title)}</strong><div class="small muted">นัดทบทวนระยะ ${x.entry.day} วัน</div><div class="actions"><button class="btn primary" onclick="startRetention('${x.skill.id}',${x.entry.day})">เช็กความจำตอนนี้</button></div></div>`).join('')}</div></div>`:'';
  document.getElementById('queue').innerHTML=[...SKILLS].sort((a,b)=>priorityScore(b)-priorityScore(a)).map(s=>{const r=state.results[s.id],ss=state.skillState[s.id];let detail='ยังไม่ได้ลองหัวข้อนี้';if(r){if(ss?.nextAction==='DEEP_REPAIR')detail='เจอจุดที่ต้องซ่อมพื้นฐาน — เรารู้ทางแล้ว 🧩';else if(ss?.nextAction==='REFRESH_REPAIR')detail='เคยทำได้ แต่ความรู้เริ่มจาง — ถึงเวลาปัดฝุ่น 🔁';else if(r.deepRepairScore===100)detail='ซ่อมพื้นฐานแล้วทำโจทย์ใหม่ได้ 💪';else if(r.freshScore===100)detail='ทำโจทย์ใหม่ได้ครบด้วยตัวเอง 🎯';else if(r.postSupportFreshScore===100)detail='หลังทบทวนแล้วทำโจทย์ใหม่ได้ 💪'}const label=ss?.nextAction==='DEEP_REPAIR'?'ซ่อมพื้นฐานจุดนี้':ss?.nextAction==='REFRESH_REPAIR'?'ทบทวนให้กลับมาแน่น':state.done[s.id]?'ลองเอาชนะรอบเก่า':'เริ่มภารกิจ';const action=ss?.nextAction==='DEEP_REPAIR'?`startDeepRepair('${s.id}')`:`start('${s.id}')`;return `<div class="module"><strong>${esc(s.title)}</strong><div class="progress"><div style="width:${state.done[s.id]?'100':'0'}%"></div></div><div class="muted small">${detail}</div>${ss?`<div class="state">${userStateEmoji(ss.status)} <strong>${esc(userStateText(ss.status))}</strong></div>`:''}<div class="actions"><button class="btn primary" onclick="${action}">${label}</button></div>${r?devDetails(`Fresh ${r.freshScore}% • Rescue ${r.rescueScore??'n/a'} • Post ${r.postSupportFreshScore??'n/a'} • Deep ${r.deepRepairScore??'n/a'} • ${ss?.status||'no state'} • next=${ss?.nextAction||'n/a'}`):''}</div>`}).join('')}
function start(id){active=SKILLS.find(s=>s.id===id);phase='diagnostic';idx=0;answers=[];conf=[];diagnosticEvidence=null;wrongEvidence=[];rescueHintLevel=0;deepPrereqEvidence=null;currentRetentionDay=null;delete state._pending;currentAttemptId='DEV-'+active.id+'-'+Date.now();attemptStartedAt=nowIso();log('module_start',{skill:id,flow:'STANDARD'});hideAll();document.getElementById('learn').classList.remove('hidden');beginItem()}
function startDeepRepair(id){active=SKILLS.find(s=>s.id===id);phase='deep_prereq';idx=0;answers=[];conf=[];deepPrereqEvidence=null;currentRetentionDay=null;currentAttemptId='DEV-DEEP-'+active.id+'-'+Date.now();attemptStartedAt=nowIso();log('deep_repair_start',{skill:id});hideAll();document.getElementById('learn').classList.remove('hidden');beginItem()}
function startRetention(id,day){active=SKILLS.find(s=>s.id===id);currentRetentionDay=day;phase='retention';idx=0;answers=[];conf=[];currentAttemptId='DEV-RET-'+active.id+'-D'+day+'-'+Date.now();attemptStartedAt=nowIso();log('retention_start',{skill:id,day});hideAll();document.getElementById('learn').classList.remove('hidden');beginItem()}
function beginItem(){itemStartAt=Date.now();renderCurrentItem()}
function currentQuestion(){if(phase==='diagnostic')return active.diagnostic;if(phase==='fresh')return active.fresh[idx];if(phase==='rescue')return active.rescue;if(phase==='post_support')return active.retest;if(phase==='deep_prereq')return active.deep.prereq;if(phase==='deep_transfer')return active.deep.transfer;if(phase==='retention')return active.retention.find(q=>q.day===currentRetentionDay);return null}
function phaseLabel(){if(phase==='diagnostic')return'เช็กพื้นฐานสั้นๆ ก่อน';if(phase==='fresh')return`ลองโจทย์ใหม่ด้วยตัวเอง ${idx+1} / ${active.fresh.length}`;if(phase==='rescue')return'มาแกะจุดที่ยังติดกัน';if(phase==='post_support')return'พิสูจน์กันอีกข้อ — คราวนี้ทำเองล้วนๆ';if(phase==='deep_prereq')return'ย้อนดูฐานรากหนึ่งชั้น';if(phase==='deep_transfer')return'ด่านใหม่หลังซ่อมพื้นฐาน';return`เช็กความจำหลัง ${currentRetentionDay} วัน`}
function phaseCoach(){if(phase==='diagnostic')return'ไม่ต้องกดดัน ข้อนี้แค่ช่วยให้เรารู้ว่าจะสอนตรงไหน';if(phase==='fresh')return'ลองด้วยตัวเองเต็มที่ ผิดได้ เพราะข้อผิดนี่แหละบอกทางให้เรา';if(phase==='rescue')return'โจทย์ตัวแสบโผล่มาแล้ว 😄 เราค่อยๆ แกะมันทีละชั้น';if(phase==='post_support')return'ด่านพิสูจน์! ไม่มีตัวช่วยแล้ว มาดูกันว่าวิธีเมื่อกี้ติดมือหรือยัง 💪';if(phase==='deep_prereq')return'เราไม่ได้ถอยหลัง เรากำลังหาอิฐก้อนที่หลวม จะได้ซ่อมถูกก้อน';if(phase==='deep_transfer')return'ซ่อมแล้วต้องลองของจริงอีกข้อ ถ้าผ่านตรงนี้ค่อยฉลองได้ 🎯';return'ไม่ต้องอ่านทวนก่อนนะ เราอยากรู้ว่าความรู้ยังอยู่จริงแค่ไหน'}
function renderCurrentItem(){const q=currentQuestion(),sel=answers[idx],cv=conf[idx];const hintBlock=phase==='rescue'&&rescueHintLevel>0?`<div class="hint"><strong>คำใบ้ ${rescueHintLevel}</strong><br>${esc(q.hints[rescueHintLevel-1])}</div>`:'';const hintButtons=phase==='rescue'?`<div class="actions">${rescueHintLevel<1?'<button class="btn light" onclick="showHint(1)">ขอคำใบ้เบาๆ 💡</button>':''}${rescueHintLevel<2?'<button class="btn light" onclick="showHint(2)">ขออีกนิด 😄</button>':''}</div>`:'';document.getElementById('pane').innerHTML=`<div class="muted">${phaseLabel()}</div><div class="coach">${phaseCoach()}</div><h2>${esc(q.p)}</h2><div class="choices">${q.c.map((x,i)=>`<button class="choice ${sel===i?'sel':''}" onclick="pick(${i})">${String.fromCharCode(65+i)}. ${esc(x)}</button>`).join('')}</div><div class="conf"><span class="muted small" style="align-self:center">ตอนตอบรู้สึกแค่ไหน?</span><button class="c ${cv===1?'on':''}" onclick="setc(1)">เดาสุดๆ 😅</button><button class="c ${cv===2?'on':''}" onclick="setc(2)">พอมั่นใจ 🙂</button><button class="c ${cv===3?'on':''}" onclick="setc(3)">มั่นใจเลย 💪</button></div>${hintBlock}${hintButtons}<div class="actions"><button class="btn primary" onclick="submitCurrent()">${phase==='fresh'&&idx<active.fresh.length-1?'ไปข้อต่อไป →':'ส่งคำตอบ'}</button><button class="btn light" onclick="exitModule()">พักก่อน</button></div>${devDetails(`phase=${phase} • question_id=${q.id} • skill=${active.id}`)}`}
function pick(i){answers[idx]=i;renderCurrentItem()}
function setc(v){conf[idx]=v;renderCurrentItem()}
function showHint(level){rescueHintLevel=Math.max(rescueHintLevel,level);log('hint_open',{skill:active.id,questionId:active.rescue.id,phase:'rescue',hintLevel:level});renderCurrentItem()}
function exitModule(){if(active&&phase!=='completed')log('module_abandon',{skill:active.id,phase,questionId:currentQuestion()?.id||null});delete state._pending;active=null;phase='idle';currentAttemptId=null;attemptStartedAt=null;currentRetentionDay=null;save();renderHome()}
function diagnose(q,selected,correct,confidence,responseTimeSec){if(correct)return confidence===1?{type:'low_confidence_correct',reason:'ตอบถูกแต่ confidence ต่ำ'}:{type:'no_error_observed',reason:'ยังไม่พบ error ในข้อนี้'};if(q.wrong&&q.wrong[selected]){const [type,reason,hint]=q.wrong[selected];return{type,reason,hint}}if(confidence===3)return{type:'misconception_risk',reason:'ตอบผิดพร้อมความมั่นใจสูง'};if(responseTimeSec>=45)return{type:'strategy_or_processing_gap',reason:'ตอบผิดและใช้เวลาค่อนข้างนาน'};if(confidence===1)return{type:'knowledge_or_prerequisite_gap',reason:'ตอบผิดพร้อม confidence ต่ำ'};return{type:'procedural_gap',reason:'ตอบผิด แต่หลักฐานยังไม่พอชี้เฉพาะจุด'}}
function submitCurrent(){const q=currentQuestion(),selected=answers[idx],confidence=conf[idx];if(selected==null||confidence==null){alert('เลือกคำตอบและบอกระดับความมั่นใจก่อนนะ');return}const correct=selected===q.a,rt=Math.max(0,Math.round((Date.now()-itemStartAt)/1000));log('item_answer',{skill:active.id,phase,questionId:q.id,selected:String.fromCharCode(65+selected),correct,confidence,responseTimeSec:rt,hintLevel:phase==='rescue'?rescueHintLevel:0,retentionDay:currentRetentionDay});const d=diagnose(q,selected,correct,confidence,rt);log('diagnosis_generated',{skill:active.id,phase,questionId:q.id,diagnosisType:d.type,reason:d.reason,evidenceStrength:'DEV_HEURISTIC'});if(phase==='diagnostic'){diagnosticEvidence={correct,confidence,responseTimeSec:rt,diagnosis:d};showLesson();return}if(phase==='fresh'){if(!correct)wrongEvidence.push({questionId:q.id,diagnosis:d,confidence,responseTimeSec:rt});if(idx<active.fresh.length-1){idx++;beginItem();return}finishFresh();return}if(phase==='rescue'){finishRescue(correct,confidence,rt,d);return}if(phase==='post_support'){finishPostSupport(correct,confidence,rt,d);return}if(phase==='deep_prereq'){deepPrereqEvidence={correct,confidence,responseTimeSec:rt};showDeepLesson();return}if(phase==='deep_transfer'){finishDeepTransfer(correct,confidence,rt);return}if(phase==='retention'){finishRetention(correct,confidence,rt);return}}
function showLesson(){phase='teach';const d=diagnosticEvidence.diagnosis;const opener=diagnosticEvidence.correct?'เริ่มได้ดี เราจะใช้ข้อใหม่เช็กให้แน่ใจอีกที':'เจอร่องรอยแล้ว! ยิ่งรู้จุดติดเร็ว ยิ่งแก้ได้เร็ว';document.getElementById('pane').innerHTML=`<h1>${esc(active.title)}</h1><div class="coach"><strong>${opener}</strong><br>${esc(diagnosisThai(d))}</div><div class="lesson"><h3>เคล็ดลับรอบนี้</h3><p>${esc(active.lesson)}</p><div class="visual">${esc(active.visual)}</div><a class="resource" target="_blank" rel="noopener" href="${active.url}" onclick="log('resource_open',{skill:active.id,url:active.url,phase:'teach'})">↗ ดูตัวอย่างเพิ่มเติมจาก สสวท.</a><div class="actions"><button class="btn primary" onclick="beginFresh()">พร้อมแล้ว ลุยโจทย์ใหม่</button><button class="btn light" onclick="exitModule()">พักก่อน</button></div></div>${devDetails(`diagnosis=${d.type} • evidence=DEV_HEURISTIC`)}`}
function beginFresh(){phase='fresh';idx=0;answers=[];conf=[];wrongEvidence=[];log('fresh_start',{skill:active.id});beginItem()}
function finishFresh(){let correct=0;active.fresh.forEach((q,i)=>{if(answers[i]===q.a)correct++});const freshScore=Math.round(correct/active.fresh.length*100),avg=(conf.reduce((a,b)=>a+b,0)/conf.length).toFixed(2);log('fresh_complete',{skill:active.id,freshScore,avgConfidence:avg,wrongCount:wrongEvidence.length});if(wrongEvidence.length===0){completeStandard({freshScore,avgConfidence:avg,rescueScore:null,postSupportFreshScore:null,rescueUsed:false});return}const lead=wrongEvidence.find(x=>x.confidence===3)||wrongEvidence[0];state._pending={freshScore,avgConfidence:avg};save();document.getElementById('pane').innerHTML=`<h1>จับได้แล้ว 1 จุด 🧩</h1><div class="feedback"><strong>รอบนี้ทำเองได้ ${Math.round(freshScore/100*active.fresh.length)} จาก ${active.fresh.length} ข้อ</strong></div><div class="coach"><strong>จุดที่น่าลองแกะ:</strong> ${esc(diagnosisThai(lead.diagnosis))}<br>ดีเลย — ตอนนี้เรารู้แล้วว่าต้องลงแรงตรงไหน แทนที่จะอ่านใหม่ทั้งบท 😄</div><div class="actions"><button class="btn primary" onclick="beginRescue()">ไปแกะจุดนี้กัน</button><button class="btn light" onclick="exitModule()">พักก่อน</button></div>${devDetails(`Fresh=${freshScore}% • diagnosis=${lead.diagnosis.type} • Fresh locked`)}`}
function beginRescue(){phase='rescue';idx=0;answers=[];conf=[];rescueHintLevel=0;log('rescue_start',{skill:active.id,wrongFreshItems:wrongEvidence.map(x=>x.questionId)});beginItem()}
function finishRescue(correct,confidence,rt,diagnosis){const pending=state._pending||{freshScore:0,avgConfidence:String(confidence)};state._pending={...pending,rescueScore:correct?100:0,rescueConfidence:confidence,hintsUsed:rescueHintLevel};log('rescue_complete',{skill:active.id,rescueScore:state._pending.rescueScore,confidence,responseTimeSec:rt,hintsUsed:rescueHintLevel,diagnosisType:diagnosis.type});save();phase='post_support';idx=0;answers=[];conf=[];log('post_support_fresh_start',{skill:active.id,questionId:active.retest.id});beginItem()}
function finishPostSupport(correct,confidence,rt){const p=state._pending||{freshScore:0,avgConfidence:String(confidence),rescueScore:null,hintsUsed:0};const postSupportFreshScore=correct?100:0;log('post_support_fresh_complete',{skill:active.id,postSupportFreshScore,confidence,responseTimeSec:rt});delete state._pending;completeStandard({freshScore:p.freshScore,avgConfidence:p.avgConfidence,rescueScore:p.rescueScore,postSupportFreshScore,rescueUsed:true,hintsUsed:p.hintsUsed})}
function completeStandard({freshScore,avgConfidence,rescueScore,postSupportFreshScore,rescueUsed,hintsUsed=0}){const status=deriveSkillStatus(freshScore,postSupportFreshScore),eligible=status!=='NEEDS_FOUNDATION_REPAIR',schedule=eligible?retentionSchedule(active):[],nextAction=eligible?'RETENTION':'DEEP_REPAIR',completedAt=nowIso();state.done[active.id]=true;state.results[active.id]={...(state.results[active.id]||{}),freshScore,rescueScore,postSupportFreshScore,avgConfidence,deepRepairScore:null,at:completedAt,label:'DEV session evidence'};state.skillState[active.id]={status,freshAccuracy:freshScore,rescueAccuracy:rescueScore,postSupportFreshAccuracy:postSupportFreshScore,deepRepairAccuracy:null,diagnosticCorrect:diagnosticEvidence?.correct??null,avgConfidence:Number(avgConfidence),supportUsed:rescueUsed,hintsUsed,lastEvidenceAt:completedAt,retentionEligible:eligible,retentionDue:schedule,nextAction};state.attemptHistory.push({attemptId:currentAttemptId,type:'STANDARD',skill:active.id,startedAt:attemptStartedAt,completedAt,diagnostic:diagnosticEvidence,freshScore,rescueScore,postSupportFreshScore,avgConfidence:Number(avgConfidence),supportUsed:rescueUsed,hintsUsed,status,retentionEligible:eligible,nextAction});log('skill_state_update',{skill:active.id,status,retentionEligible:eligible,nextAction});if(eligible)log('retention_scheduled',{skill:active.id,schedule});else log('deep_repair_required',{skill:active.id,reason:'post_support_transfer_not_passed'});save();phase='completed';showCompletion(status,eligible)}
function showCompletion(status,eligible){const r=state.results[active.id];const headline=status==='TENTATIVE_MASTERY_DEV'?'ผ่านด่านนี้แบบไม่ต้องช่วย 🎯':status==='TRANSFER_AFTER_SUPPORT_DEV'?'เยี่ยม! วิธีที่ทบทวนไปเริ่มติดมือแล้ว 💪':'ยังไม่จบเกม — แต่ตอนนี้เรารู้ว่าจะซ่อมตรงไหน 🧩';const body=eligible?'รอบนี้มีหลักฐานว่าทำโจทย์ใหม่ได้แล้ว ต่อไปเราจะกลับมาเช็กภายหลังว่ายังจำได้จริงไหม':'โจทย์ใหม่หลังทบทวนยังไม่ผ่าน เราจะไม่ส่งไปทบทวนระยะยาวแบบหลอกตัวเอง รอบถัดไปจะย้อนซ่อมฐานรากหนึ่งชั้น';document.getElementById('pane').innerHTML=`<h1>${headline}</h1><div class="feedback"><strong>ทำเองก่อนช่วย: ${r.freshScore}%${r.rescueScore==null?'':` • รอบช่วย: ${r.rescueScore}%`}${r.postSupportFreshScore==null?'':` • โจทย์ใหม่หลังทบทวน: ${r.postSupportFreshScore}%`}</strong></div><div class="coach">${body}</div><div class="next"><strong>ก้าวต่อไป</strong><br>${eligible?'นัดเช็กความจำ 1 / 3 / 7 / 21 วัน':'ซ่อมพื้นฐาน → ลองข้อใหม่ → ผ่านแล้วค่อยนัดทบทวน'}</div><div class="actions">${eligible?'<button class="btn primary" onclick="finishAndHome()">กลับไปเลือกภารกิจ</button>':`<button class="btn primary" onclick="startDeepRepair('${active.id}')">ซ่อมพื้นฐานต่อเลย</button><button class="btn light" onclick="finishAndHome()">พักก่อน</button>`}</div>${devDetails(`state=${status} • next=${eligible?'RETENTION':'DEEP_REPAIR'} • retentionEligible=${eligible}`)}`}
function showDeepLesson(){phase='deep_teach';const msg=deepPrereqEvidence.correct?'ฐานก้อนนี้ยังโอเค แปลว่าจุดติดน่าจะอยู่ที่การเชื่อมขั้นตอน':'เจอก้อนฐานที่หลวมแล้ว 🎯 รอบนี้เราจะซ่อมเฉพาะก้อนนี้ก่อน';log('deep_prereq_complete',{skill:active.id,correct:deepPrereqEvidence.correct});document.getElementById('pane').innerHTML=`<h1>ซ่อมให้ถูกจุด ไม่อ่านใหม่ทั้งบท</h1><div class="coach"><strong>${msg}</strong></div><div class="lesson"><h3>มองอีกมุมหนึ่ง</h3><p>${esc(active.deep.lesson)}</p><div class="visual">${esc(active.deep.visual)}</div><div class="actions"><button class="btn primary" onclick="beginDeepTransfer()">ลองข้อใหม่หลังซ่อม</button><button class="btn light" onclick="exitModule()">พักก่อน</button></div></div>${devDetails(`deepPrereqCorrect=${deepPrereqEvidence.correct}`)}`}
function beginDeepTransfer(){phase='deep_transfer';idx=0;answers=[];conf=[];log('deep_transfer_start',{skill:active.id,questionId:active.deep.transfer.id});beginItem()}
function finishDeepTransfer(correct,confidence,rt){const score=correct?100:0,completedAt=nowIso(),eligible=correct,schedule=eligible?retentionSchedule(active):[],status=eligible?'TRANSFER_AFTER_DEEP_REPAIR_DEV':'NEEDS_FOUNDATION_REPAIR',nextAction=eligible?'RETENTION':'DEEP_REPAIR';const old=state.results[active.id]||{};state.done[active.id]=true;state.results[active.id]={...old,deepRepairScore:score,deepRepairAt:completedAt};state.skillState[active.id]={...(state.skillState[active.id]||{}),status,deepRepairAccuracy:score,lastEvidenceAt:completedAt,retentionEligible:eligible,retentionDue:schedule,nextAction};state.attemptHistory.push({attemptId:currentAttemptId,type:'DEEP_REPAIR',skill:active.id,startedAt:attemptStartedAt,completedAt,prereq:deepPrereqEvidence,deepTransferScore:score,confidence,responseTimeSec:rt,status,retentionEligible:eligible,nextAction});log('deep_transfer_complete',{skill:active.id,score,status,retentionEligible:eligible});if(eligible)log('retention_scheduled',{skill:active.id,schedule,source:'DEEP_REPAIR'});save();phase='completed';document.getElementById('pane').innerHTML=`<h1>${eligible?'ซ่อมสำเร็จ! คราวนี้ทำข้อใหม่ได้เอง 💪':'ยังไม่ผ่าน — แต่เราแคบวงปัญหาได้อีกขั้น 🧩'}</h1><div class="coach">${eligible?'นี่คือสิ่งที่เราต้องการเห็น: ไม่ใช่ทำข้อช่วยถูก แต่เป็นการทำโจทย์ใหม่หลังซ่อมได้ด้วยตัวเอง':'ระบบจะยังไม่รีบตีตราว่า “ไม่เก่ง” และยังไม่ส่งไปทบทวนระยะยาว เราจะเก็บหลักฐานเพิ่มและเปลี่ยนวิธีสอนในรอบหน้า'}</div><div class="next"><strong>ก้าวต่อไป</strong><br>${eligible?'เริ่มนัดเช็กความจำ 1 / 3 / 7 / 21 วัน':'ยังอยู่ในเส้นทางซ่อมพื้นฐาน และต้องใช้โจทย์/วิธีสอนอีกชุดในเวอร์ชันถัดไป'}</div><div class="actions"><button class="btn primary" onclick="finishAndHome()">กลับไปหน้าภารกิจ</button></div>${devDetails(`deepTransfer=${score}% • state=${status} • retentionEligible=${eligible}`)}`}
function finishRetention(correct,confidence,rt){const ss=state.skillState[active.id]||{},entry=(ss.retentionDue||[]).find(x=>x.day===currentRetentionDay&&x.status==='PENDING');if(!entry){alert('ไม่พบรายการทบทวนที่กำหนดไว้');finishAndHome();return}entry.status='DONE';entry.completedAt=nowIso();entry.correct=correct;const result={attemptId:currentAttemptId,skill:active.id,day:currentRetentionDay,questionId:currentQuestion().id,correct,confidence,responseTimeSec:rt,completedAt:entry.completedAt};state.retentionHistory.push(result);if(correct){const allDone=ss.retentionDue.every(x=>x.status==='DONE');ss.status=allDone?'RETENTION_CONFIRMED_DEV':ss.status;ss.nextAction='RETENTION';ss.retentionEligible=true;log('retention_complete',{...result,allDone})}else{ss.status='RETENTION_WEAK_DEV';ss.nextAction='REFRESH_REPAIR';ss.retentionEligible=false;ss.retentionDue.forEach(x=>{if(x.status==='PENDING')x.status='PAUSED_AFTER_MISS'});log('retention_complete',{...result,remainingPaused:true})}ss.lastEvidenceAt=entry.completedAt;state.skillState[active.id]=ss;save();phase='completed';document.getElementById('pane').innerHTML=`<h1>${correct?'ยังอยู่! ความรู้ไม่ได้หายไปไหน 🎯':'จับได้ก่อนสอบจริง — ความรู้เริ่มจางนิดหนึ่ง 🔁'}</h1><div class="coach">${correct?'ทำโจทย์ใหม่ได้โดยไม่อ่านทวนก่อน นี่คือหลักฐาน retention ที่เราต้องการ':'นี่ไม่ใช่ความล้มเหลว การลืมเป็นข้อมูลสำคัญ ระบบจะหยุดตารางเดิมและพากลับไปปัดฝุ่นก่อน'}</div><div class="next"><strong>ก้าวต่อไป</strong><br>${correct?'เดินตามนัดทบทวนที่เหลือต่อไป':'ทบทวนสั้นๆ → ทำโจทย์ใหม่ → ผ่านแล้วค่อยตั้งรอบจำใหม่'}</div><div class="actions"><button class="btn primary" onclick="finishAndHome()">กลับหน้าภารกิจ</button></div>${devDetails(`retentionDay=${currentRetentionDay} • correct=${correct} • state=${ss.status} • next=${ss.nextAction}`)}`}
function finishAndHome(){active=null;phase='idle';currentAttemptId=null;attemptStartedAt=null;currentRetentionDay=null;renderHome()}
function showTelemetry(){hideAll();document.getElementById('telemetry').classList.remove('hidden');document.getElementById('telemetryBox').textContent=JSON.stringify({skillState:state.skillState,attemptHistory:state.attemptHistory,retentionHistory:state.retentionHistory,events:state.events},null,2)}
function devMakeNextRetentionDue(){const pending=[];SKILLS.forEach(s=>{(state.skillState[s.id]?.retentionDue||[]).forEach(r=>{if(r.status==='PENDING')pending.push({s,r})})});pending.sort((a,b)=>Date.parse(a.r.dueAt)-Date.parse(b.r.dueAt));if(!pending.length){alert('ยังไม่มี Retention ที่รออยู่ — ต้องผ่าน Transfer ก่อน');return}pending[0].r.dueAt=new Date(Date.now()-1000).toISOString();log('dev_retention_forced_due',{skill:pending[0].s.id,day:pending[0].r.day});renderHome()}
function copySummary(){const lines=['KIDS LEARNING HUB — ADULT DEV TESTER',state.profile.tester+' • '+state.profile.scenario,'App '+APP_VERSION,''];SKILLS.forEach(s=>{const r=state.results[s.id],ss=state.skillState[s.id];lines.push(s.title+': '+(r?`Fresh ${r.freshScore}% | Post ${r.postSupportFreshScore??'n/a'} | Deep ${r.deepRepairScore??'n/a'} | ${ss?.status||'no state'} | next ${ss?.nextAction||'n/a'}`:'pending'))});lines.push('Learning attempts: '+state.attemptHistory.length,'Retention checks: '+state.retentionHistory.length,'Events: '+state.events.length);const text=lines.join('\n');navigator.clipboard?.writeText(text).then(()=>alert('คัดลอกผลแล้ว')).catch(()=>prompt('คัดลอกข้อความนี้',text))}
function downloadJSON(){const blob=new Blob([JSON.stringify({meta:{mode:'ADULT_DEV_TEST',appVersion:APP_VERSION,contentVersion:CONTENT_VERSION,eventSchemaVersion:EVENT_SCHEMA_VERSION,exportedAt:nowIso()},profile:state.profile,results:state.results,skillState:state.skillState,attemptHistory:state.attemptHistory,retentionHistory:state.retentionHistory,events:state.events},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='klh_dev_tester_session_v060.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function resetApp(){if(confirm('ล้างข้อมูลทดสอบใน browser เครื่องนี้?')){localStorage.removeItem(KEY);LEGACY_KEYS.forEach(k=>localStorage.removeItem(k));location.reload()}}
if(state.profile)renderHome();
