// Kids Learning Hub — Learner Twin + Tutor Policy + Experience Composer DEV v0.13
(function(){
'use strict';
const V='0.13.0-dev',CTX_KEY='KLH_V013_CONTEXT',TWIN_KEY='KLH_V013_LEARNER_TWIN';
const INTERESTS=[['game','🎮 เกม'],['robot','🤖 Robot / Lego'],['science','🧪 ทดลองวิทย์'],['art','🎨 วาด/ศิลปะ'],['food','🍜 อาหาร/ทำครัว'],['sport','⚽ กีฬา'],['music','🎵 ดนตรี'],['story','🕵️ เรื่องลึกลับ']];
const SUBJECTS={math:{name:'คณิตศาสตร์',icon:'🧮',tone:'violet',desc:'คิดเป็นขั้น • แก้โจทย์ • เตรียมสอบ'},science:{name:'วิทยาศาสตร์',icon:'🔬',tone:'mint',desc:'ทดลอง • หาเหตุผล • เชื่อมโยง'},english:{name:'ภาษาอังกฤษ',icon:'🌍',tone:'sky',desc:'อ่าน • ฟัง • ใช้จริง'},thai:{name:'ภาษาไทย',icon:'📚',tone:'sun',desc:'อ่านโจทย์ • จับใจความ • สื่อสาร'},chinese:{name:'ภาษาจีน',icon:'🀄',tone:'rose',desc:'เข้าใจภาษา • ใช้จริง • ค่อยๆสะสม'}};
const TOPICS={
 math:[
  {id:'division',title:'การหารด้วยตัวหาร 2 หลัก',sourceGrade:4,lesson:'การหารแบบนี้ง่ายขึ้นมากถ้าเปลี่ยนคำถามจาก “หารยังไง” เป็น “ตัวหารคูณกี่ครั้งจึงได้จำนวนนี้” แล้วค่อยคูณกลับเพื่อตรวจ',visual:'3,600 ÷ 24 = ?  →  24 × ? = 3,600',q:{p:'2,880 ÷ 24 = ?',c:['100','110','120','140'],a:2},alt:'ลองแยกเป็นก้อน: 24×100 = 2,400 เหลือ 480 และ 24×20 = 480 ดังนั้น 100+20 = 120'},
  {id:'fraction',title:'เศษส่วนของเศษส่วน',sourceGrade:5,lesson:'เวลาเห็นคำว่า “ของ” ให้แปลเป็นเครื่องหมายคูณก่อน เช่น 1/2 ของ 3/4 = 1/2 × 3/4 แล้วจึงตัดทอน',visual:'1/2 ของ 3/4  →  1/2 × 3/4  →  3/8',q:{p:'มีเค้ก 3/4 ก้อน กินไป 1/3 ของที่มี กินไปเท่าไร?',c:['1/4','1/3','1/2','2/3'],a:0},alt:'นึกเป็นภาพ: มีเค้ก 3 ส่วนจาก 4 ส่วน แล้วเอาเพียง 1 ใน 3 ของส่วนที่มี จึงเหลือปริมาณที่กินเท่ากับ 1/4 ก้อน'},
  {id:'decimal',title:'หารทศนิยมด้วยทศนิยม',sourceGrade:6,lesson:'ทำตัวหารให้เป็นจำนวนเต็มก่อน โดยเลื่อนจุดทศนิยมของทั้งตัวตั้งและตัวหาร “เท่ากัน” แล้วค่อยหารตามปกติ',visual:'2.4 ÷ 0.15  →  240 ÷ 15  →  16',q:{p:'1.8 ÷ 0.2 = ?',c:['6','7','8','9'],a:3},alt:'คิดว่า 0.2 ต้องกี่ชุดจึงรวมเป็น 1.8? สิบชุดจะเป็น 2.0 ดังนั้นเก้าชุดคือ 1.8'}
 ],
 science:[{id:'science_reasoning',title:'นักวิทย์คิดอย่างไรเวลาเจอปัญหา',sourceGrade:null,lesson:'เริ่มจากแยก “สิ่งที่สังเกตได้” ออกจาก “สิ่งที่เราคิดว่าเป็นสาเหตุ” แล้วค่อยออกแบบวิธีตรวจว่าแนวคิดไหนถูก',visual:'สังเกต → ตั้งสมมติฐาน → ทดลอง → ดูหลักฐาน',q:{p:'ต้นไม้ต้นหนึ่งโตช้ากว่าต้นอื่น สิ่งแรกที่นักวิทยาศาสตร์ควรทำคืออะไร?',c:['สรุปว่าปุ๋ยไม่ดีทันที','เก็บข้อมูลแสง น้ำ ดิน และตัวแปรอื่นก่อน','เปลี่ยนต้นไม้ทันที','เดาคำตอบที่น่าจะใช่'],a:1},alt:'นักวิทย์ไม่รีบสรุปจากสิ่งเดียว เขาจะหาหลักฐานที่แยกสาเหตุออกจากกันก่อน'}],
 english:[{id:'english_reading',title:'อ่านอังกฤษให้จับใจความเร็วขึ้น',sourceGrade:null,lesson:'อย่าแปลทุกคำ เริ่มจากหา “ใคร/อะไร + ทำอะไร + เพราะอะไร” แล้วค่อยกลับไปดูคำที่จำเป็น',visual:'WHO / WHAT → ACTION → WHY',q:{p:'Tom missed the bus because he woke up late. Why did Tom miss the bus?',c:['He was sick.','He woke up late.','The bus was broken.','He forgot his bag.'],a:1},alt:'มองหา because ก่อน เพราะส่วนหลัง because มักบอกเหตุผลของประโยคนี้'},],
 thai:[{id:'thai_mainidea',title:'จับใจความสำคัญจากข้อความ',sourceGrade:null,lesson:'ใจความสำคัญไม่ใช่รายละเอียดที่จำได้มากที่สุด แต่คือประโยคที่อธิบายได้ว่าข้อความทั้งหมดกำลังพูดเรื่องอะไร',visual:'รายละเอียดหลายข้อ → รวมเป็น “เรื่องหลักเดียว”',q:{p:'ข้อความเล่าว่าเด็กๆปลูกต้นไม้ รดน้ำทุกวัน และช่วยกันเก็บขยะในสวน ใจความสำคัญควรเป็นข้อใด?',c:['เด็กชอบรดน้ำ','เด็กช่วยกันดูแลสวน','สวนมีขยะ','ต้นไม้ต้องการน้ำ'],a:1},alt:'ถามตัวเองว่า “ถ้าต้องเล่าเรื่องนี้ให้เพื่อนฟังในหนึ่งประโยค จะพูดว่าอะไร”'}],
 chinese:[{id:'chinese_pattern',title:'จับแพตเทิร์นประโยคจีนง่ายๆ',sourceGrade:null,lesson:'เริ่มจากมองตำแหน่งคำ ไม่ต้องท่องทั้งประโยค เช่น 我喜欢___ = ฉันชอบ___ แล้วเปลี่ยนคำท้ายได้หลายอย่าง',visual:'我喜欢 + สิ่งที่ชอบ',q:{p:'ถ้า 我喜欢苹果 แปลว่า “ฉันชอบแอปเปิล” คำว่า 喜欢 ทำหน้าที่ใกล้เคียงคำใด?',c:['ฉัน','ชอบ','แอปเปิล','กิน'],a:1},alt:'ลองแทน 苹果 ด้วย 游戏 (เกม) จะได้ 我喜欢游戏 — โครงเดิมแต่เปลี่ยนสิ่งที่ชอบ'}]
};
const SCHOOL_PROFILES={
 'โรงเรียนอัสสัมชัญลำปาง':{authority:'สช. / โรงเรียนเอกชน',operator:'มูลนิธิคณะเซนต์คาเบรียลแห่งประเทศไทย',status:'PARTIAL',note:'รู้สังกัดและเครือแล้ว แต่ลำดับบทเรียนรายชั้น/เทอมต้องยืนยันเพิ่มก่อนใช้วัด mastery'},
 'โรงเรียนวิทยาศาสตร์จุฬาภรณราชวิทยาลัย ลำปาง':{authority:'สพฐ. / เครือโรงเรียนวิทยาศาสตร์จุฬาภรณราชวิทยาลัย',operator:'โรงเรียนวิทยาศาสตร์จุฬาภรณราชวิทยาลัย',status:'PARTIAL',note:'รู้เครือและแนวหลักสูตร แต่ยังต้องยืนยัน course map รายชั้น/เทอม'}
};
let schools=[],interestSet=new Set(),subject='math',mode='learn',activeTopic=null,lessonStartedAt=0,lastStrategy='direct';
function $(id){return document.getElementById(id)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function show(id){['setup','home','subject','work'].forEach(x=>$(x)?.classList.toggle('hidden',x!==id));window.scrollTo({top:0,behavior:'smooth'});}
function read(k,fallback=null){try{return JSON.parse(localStorage.getItem(k)||'null')??fallback}catch(e){return fallback}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function ctx(){return read(CTX_KEY,null)}
function twin(){return read(TWIN_KEY,{version:V,createdAt:new Date().toISOString(),events:[],topics:{},strategy:{direct:1,analogy:1,visual:1,prediction:1,teachback:1,prereq:1},signals:{altExplain:0,firstTryCorrect:0,wrong:0,correct:0,returns:0}})}
function saveTwin(t){t.updatedAt=new Date().toISOString();write(TWIN_KEY,t)}
function event(type,data={}){const t=twin();t.events.push({at:new Date().toISOString(),type,...data});if(t.events.length>300)t.events=t.events.slice(-300);saveTwin(t)}
function topicState(id){const t=twin();return t.topics[id]||{seen:0,learn:0,practice:0,correct:0,wrong:0,alt:0,last:null,exposure:'UNKNOWN'};}
function updateTopic(id,patch){const t=twin(),s=t.topics[id]||topicState(id);Object.assign(s,patch,{last:new Date().toISOString()});t.topics[id]=s;saveTwin(t)}
function incSignal(k,n=1){const t=twin();t.signals[k]=(t.signals[k]||0)+n;saveTwin(t)}
function scoreStrategy(k,n){const t=twin();t.strategy[k]=Math.max(.1,(t.strategy[k]||1)+n);saveTwin(t)}
function setExposure(id,v){updateTopic(id,{exposure:v});event('exposure',{topic:id,value:v});}

function fillSelect(id,list,placeholder){const s=$(id);s.innerHTML=`<option value="" selected disabled>${placeholder}</option>`+list.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')+'<option value="__OTHER__">โรงเรียนอื่นๆ</option>';}
async function loadSchools(){try{const txt=await fetch('../school-target-autocomplete-v011.js?v=0.13.0').then(r=>r.text()),m=txt.match(/const S=(\[[\s\S]*?\]);\nconst A=/);schools=m?JSON.parse(m[1]):[];}catch(e){}if(!schools.length)schools=['โรงเรียนอัสสัมชัญลำปาง','โรงเรียนบุญวาทย์วิทยาลัย','โรงเรียนลำปางกัลยาณี','โรงเรียนวิทยาศาสตร์จุฬาภรณราชวิทยาลัย ลำปาง','โรงเรียนมหิดลวิทยานุสรณ์','โรงเรียนกำเนิดวิทย์','โรงเรียนเตรียมอุดมศึกษา'];fillSelect('school',schools,'เลือกโรงเรียนที่เรียนอยู่');fillSelect('targetSchool',schools,'เลือกโรงเรียนเป้าหมาย');restore();}
function selectedSchool(id,other){const v=$(id).value;return v==='__OTHER__'?$(other).value.trim():v;}
function syncFields(){const g=$('goal').value,target=['target','intensive'].includes(g);$('targetFields').classList.toggle('hidden',!target);$('schoolOther').classList.toggle('hidden',$('school').value!=='__OTHER__');$('targetOther').classList.toggle('hidden',$('targetSchool').value!=='__OTHER__');schoolInfo();}
function schoolInfo(){const s=selectedSchool('school','schoolOther'),box=$('schoolInfo');if(!s){box.innerHTML='';return;}const p=SCHOOL_PROFILES[s];if(p)box.innerHTML=`<div class="school-profile"><strong>✓ พบข้อมูลโรงเรียนเบื้องต้น</strong><br>${esc(p.authority)} • ${esc(p.operator)}<br><span class="help">${esc(p.note)}</span></div>`;else box.innerHTML=`<div class="school-profile pending"><strong>🔎 บันทึกโรงเรียนแล้ว</strong><br><span class="help">DEV นี้ยังไม่ได้เชื่อม School Resolver แบบสด จึงจะไม่เดาหลักสูตรรายบทของโรงเรียนนี้</span></div>`;}
function renderInterests(){const box=$('interests');box.innerHTML=INTERESTS.map(([id,label])=>`<button type="button" class="interest ${interestSet.has(id)?'on':''}" onclick="KLH.toggleInterest('${id}')">${label}</button>`).join('');}
function restore(){const c=ctx();if(c){$('name').value=c.name||'';$('grade').value=String(c.grade||'');$('term').value=String(c.term||'');$('goal').value=c.goal||'';setSchool('school','schoolOther',c.school);setSchool('targetSchool','targetOther',c.targetSchool);$('targetLevel').value=c.targetLevel||'';interestSet=new Set(c.interests||[]);}renderInterests();syncFields();}
function setSchool(id,other,value){if(!value)return;const s=$(id);if([...s.options].some(o=>o.value===value))s.value=value;else{s.value='__OTHER__';$(other).value=value;}}
function validate(){if(!$('name').value.trim())return'ใส่ชื่อเล่นก่อน';if(!$('school').value)return'เลือกโรงเรียนที่เรียนอยู่';if($('school').value==='__OTHER__'&&!$('schoolOther').value.trim())return'พิมพ์ชื่อโรงเรียนที่เรียนอยู่';if(!$('grade').value)return'เลือกชั้นเรียน';if(!$('term').value)return'เลือกเทอม';if(!$('goal').value)return'เลือกเป้าหมาย';if(['target','intensive'].includes($('goal').value)){if(!$('targetSchool').value)return'เลือกโรงเรียนเป้าหมาย';if($('targetSchool').value==='__OTHER__'&&!$('targetOther').value.trim())return'พิมพ์ชื่อโรงเรียนเป้าหมาย';if(!$('targetLevel').value)return'เลือกระดับที่จะสอบเข้า';}return'';}
function start(){const e=validate();if(e){$('setupError').textContent=e;$('setupError').classList.remove('hidden');return;}$('setupError').classList.add('hidden');const c={name:$('name').value.trim(),school:selectedSchool('school','schoolOther'),grade:Number($('grade').value),term:Number($('term').value),goal:$('goal').value,targetSchool:selectedSchool('targetSchool','targetOther'),targetLevel:$('targetLevel').value||'',interests:[...interestSet],version:V};write(CTX_KEY,c);const t=twin();t.profile={...c};saveTwin(t);event('onboarding_complete',{grade:c.grade,term:c.term,goal:c.goal,interests:c.interests.length});home();}
function toggleInterest(id){if(interestSet.has(id))interestSet.delete(id);else if(interestSet.size<3)interestSet.add(id);renderInterests();}
function goalText(c){return{school:'เรียนให้ทันโรงเรียน',foundation:'ปูพื้นฐานให้แน่น',advance:'เรียนล่วงหน้าแบบพอดี',target:'เตรียมสอบโรงเรียนเป้าหมาย',intensive:'เตรียมสอบแบบเข้มข้น'}[c.goal]||'';}
function intensity(c){return c.goal==='intensive'?'เข้มข้น 30–40 นาที':c.goal==='target'?'ติวเป้าหมาย 20–30 นาที':c.goal==='advance'?'ล่วงหน้า 20 นาที':'พอดี 15–20 นาที';}
function subjectOrder(c){if(/จุฬาภรณ|PCSHS/i.test(c.targetSchool||''))return['math','science','english','thai'];return['math','thai','science','english','chinese'];}
function home(){const c=ctx();if(!c)return show('setup');show('home');$('greeting').textContent=`${c.name} วันนี้อยากเก่งขึ้นเรื่องไหน?`;$('context').innerHTML=`<strong>ป.${c.grade} เทอม ${c.term}</strong> • ${esc(c.school)}<br>${esc(goalText(c))}${c.targetSchool?` → <strong>${esc(c.targetSchool)} ${esc(c.targetLevel)}</strong>`:''}`;$('intensity').textContent=intensity(c);$('coach').innerHTML=coach(c);$('subjects').innerHTML=subjectOrder(c).map((id,i)=>{const s=SUBJECTS[id],priority=i<2&&['target','intensive'].includes(c.goal);return`<button class="subject ${s.tone}" onclick="KLH.openSubject('${id}')"><span class="ic">${s.icon}</span><span><strong>${s.name}</strong><small>${s.desc}</small>${priority?'<em>สำคัญต่อเป้าหมาย</em>':''}</span><span class="arrow">›</span></button>`}).join('');$('twinHome').innerHTML=twinSummary();event('home_view');}
function coach(c){const t=twin(),tried=Object.values(t.topics||{}).filter(x=>x.learn||x.practice).length;if(!tried)return`<div class="coach"><div class="avatar">✨</div><div><small>ครู AI แนะนำวันนี้</small><h2>เริ่มจากวิชาที่สำคัญต่อเป้าหมาย แล้วให้ครูเรียนรู้วิธีที่ ${esc(c.name)} เข้าใจดีที่สุด</h2><p>ครั้งแรกครูจะทดลองวิธีสอนหลายแบบเล็กน้อย แล้วเก็บเฉพาะวิธีที่ช่วยให้ทำโจทย์ใหม่ได้จริง</p></div></div>`;const best=bestStrategyLabel();return`<div class="coach"><div class="avatar">🧠</div><div><small>Learner Twin กำลังเรียนรู้</small><h2>ตอนนี้วิธีที่มีสัญญาณดีที่สุดคือ “${best}”</h2><p>นี่เป็นสมมติฐานจากการใช้งาน ไม่ใช่ป้ายติดตัวเด็ก ระบบจะเปลี่ยนเมื่อมีหลักฐานใหม่</p></div></div>`;}
function twinSummary(){const t=twin(),s=t.signals||{},best=bestStrategyLabel();return`<div class="twin-grid"><div class="mini"><span>ตอบถูก</span><strong>${s.correct||0}</strong></div><div class="mini"><span>ขออธิบายอีกแบบ</span><strong>${s.altExplain||0}</strong></div><div class="mini"><span>กลยุทธ์ที่กำลังลอง</span><strong>${esc(best)}</strong></div></div>`;}
function bestStrategy(){const s=twin().strategy||{};return Object.entries(s).sort((a,b)=>b[1]-a[1])[0]?.[0]||'direct';}
function bestStrategyLabel(){return{direct:'อธิบายตรงๆ',analogy:'โยงกับของใกล้ตัว',visual:'เห็นภาพก่อนสูตร',prediction:'เดาก่อนเฉลย',teachback:'สอน AI กลับ',prereq:'ถอยหนึ่งขั้น'}[bestStrategy()]||'อธิบายตรงๆ';}
function openSubject(id){subject=id;const s=SUBJECTS[id];show('subject');$('subjectHero').innerHTML=`<div class="big">${s.icon}</div><div><span class="eyebrow">เลือกว่าจะทำอะไร</span><h1>${s.name}</h1><p>${s.desc}</p></div>`;$('modes').innerHTML=[['learn','🤖','เรียนกับ AI','ครูเลือกวิธีอธิบายตามการตอบของเรา'],['practice','🎯','ฝึกทำโจทย์','ฝึกเรื่องที่เคยเรียนแล้วให้คล่อง'],['exam','🏁','ลองข้อสอบ','Mini Test / โจทย์เป้าหมายเมื่อพร้อม']].map(x=>`<button class="mode" onclick="KLH.openMode('${x[0]}')"><span class="ic">${x[1]}</span><span><strong>${x[2]}</strong><small>${x[3]}</small></span><b>›</b></button>`).join('');event('subject_open',{subject:id});}
function openMode(m){mode=m;renderTopics();}
function renderTopics(){show('work');const c=ctx(),s=SUBJECTS[subject],arr=TOPICS[subject]||[];$('pane').innerHTML=`<button class="back" onclick="KLH.openSubject('${subject}')">← กลับ ${s.name}</button><div class="subjecthero"><div class="big">${mIcon(mode)}</div><div><span class="eyebrow">${mTitle(mode)}</span><h1>${mode==='learn'?'เลือกเรื่องที่อยากเรียน':mode==='practice'?'เลือกเรื่องที่จะฝึก':'เลือกเรื่องที่จะลองทดสอบ'}</h1><p>${mode==='learn'?'เรียนก่อน ไม่ต้องรู้มาก่อน':mode==='practice'?'ถ้ายังไม่เคยเรียน ครูจะพากลับไปเรียนก่อน':'เราจะแยกคะแนนฝึกออกจากการเรียนล่วงหน้า'}</p></div></div><div class="topic-list">${arr.map(t=>{const future=t.sourceGrade&&t.sourceGrade>c.grade;return`<button class="topic ${future?'future':''}" onclick="KLH.chooseTopic('${t.id}')"><div><strong>${esc(t.title)}</strong><small>${future?'เนื้อหาล่วงหน้า • เรียนได้ แต่ไม่ใช้ตีความว่าอ่อน':t.sourceGrade?'ครูจะเช็กก่อนว่าเคยเรียนแล้วหรือยัง':'ทักษะทั่วไป • ไม่ผูกกับลำดับบทของโรงเรียน'}</small></div><span>›</span></button>`}).join('')}</div>`;}
function mIcon(m){return m==='learn'?'🤖':m==='practice'?'🎯':'🏁'}function mTitle(m){return m==='learn'?'เรียนกับ AI':m==='practice'?'ฝึกทำโจทย์':'ลองข้อสอบ'}
function findTopic(id){for(const a of Object.values(TOPICS)){const t=a.find(x=>x.id===id);if(t)return t;}return null;}
function chooseTopic(id){activeTopic=findTopic(id);if(!activeTopic)return;const c=ctx(),st=topicState(id),future=activeTopic.sourceGrade&&activeTopic.sourceGrade>c.grade;if(mode==='learn')return tutor(id);if(future)return safetyDecision(id,true);if(st.exposure==='LEARNED')return practice(id,mode);if(st.exposure==='NOT_YET')return tutor(id);safetyDecision(id,false);}
function safetyDecision(id,future){const t=findTopic(id);show('work');$('pane').innerHTML=`<button class="back" onclick="KLH.renderTopics()">← กลับ</button><div class="decision"><div class="big">🧭</div><h1>${esc(t.title)}</h1><p class="question">${future?'เรื่องนี้อยู่ข้างหน้าระดับที่กำลังเรียน — อยากเรียนล่วงหน้าหรือไว้ก่อน?':'เรื่องนี้เคยเรียนที่โรงเรียนแล้วหรือยัง?'}</p><div class="decision-actions">${future?`<button class="yes" onclick="KLH.learnFuture('${id}')">อยากเรียนล่วงหน้า</button><button class="no" onclick="KLH.renderTopics()">ไว้ก่อน</button>`:`<button class="yes" onclick="KLH.learned('${id}')">เคยเรียนแล้ว</button><button class="no" onclick="KLH.notYet('${id}')">ยังไม่ได้เรียน</button>`}</div><div class="help">ครูไม่ใช้คำตอบ “ยังไม่ได้เรียน” เป็นคะแนนลบ</div></div>`;}
function learned(id){setExposure(id,'LEARNED');practice(id,mode);}
function notYet(id){setExposure(id,'NOT_YET');tutor(id);}
function learnFuture(id){setExposure(id,'PREVIEW');tutor(id);}
function chooseStrategy(id){const st=topicState(id),t=twin();if(st.wrong>=2)return'prereq';if(st.alt>=1&&st.correct<1)return'visual';if((t.signals?.correct||0)>=2&&st.correct>=1)return'teachback';const interests=ctx()?.interests||[];if(interests.length&&st.seen<2)return'analogy';if(st.seen<1)return'prediction';return bestStrategy();}
function interestScenario(topic){const ints=ctx()?.interests||[],pick=ints[0]||'story';const map={game:{division:'เกมมีเหรียญ 2,880 เหรียญ แบ่งเป็นแพ็กละ 24 เหรียญ ต้องสร้างกี่แพ็ก?',fraction:'พลังในเกมเหลือ 3/4 แล้วใช้สกิลไป 1/3 ของพลังที่มี ใช้ไปเท่าไร?',decimal:'ไอเท็มราคา 0.2 เหรียญ ถ้ามี 1.8 เหรียญ ซื้อได้กี่ชิ้น?'},robot:{division:'หุ่นยนต์มีชิ้นส่วน 2,880 ชิ้น กล่องหนึ่งใส่ 24 ชิ้น ต้องใช้กี่กล่อง?',fraction:'แบตหุ่นยนต์เหลือ 3/4 แล้วภารกิจใช้ 1/3 ของแบตที่มี ใช้ไปเท่าไร?'},food:{division:'ร้านเตรียมของ 2,880 ชิ้น จัดถาดละ 24 ชิ้น ต้องใช้กี่ถาด?',fraction:'มีเค้ก 3/4 ก้อน ใช้ทำของหวาน 1/3 ของที่มี ใช้ไปเท่าไร?',decimal:'น้ำซอส 1.8 ลิตร แบ่งขวดละ 0.2 ลิตร ได้กี่ขวด?'},science:{division:'ห้องทดลองมีตัวอย่าง 2,880 ชิ้น แบ่งชุดละ 24 ชิ้น ได้กี่ชุด?',fraction:'สารละลายมี 3/4 ถัง ใช้ทดลอง 1/3 ของที่มี ใช้ไปเท่าไร?'},art:{division:'มีเม็ดสี 2,880 เม็ด จัดชุดละ 24 เม็ด ได้กี่ชุด?',fraction:'สีเหลือ 3/4 กระปุก ใช้ไป 1/3 ของที่มี ใช้ไปเท่าไร?'},sport:{division:'มีแต้มฝึก 2,880 แต้ม แบ่งเป็นเซ็ตละ 24 แต้ม ได้กี่เซ็ต?',fraction:'พลังนักกีฬาเหลือ 3/4 แล้วใช้ไป 1/3 ของที่มี ใช้ไปเท่าไร?'},music:{division:'มีจังหวะฝึก 2,880 beat แบ่งช่วงละ 24 beat ได้กี่ช่วง?',fraction:'เพลงยาว 3/4 นาที เล่นไป 1/3 ของช่วงนั้น เล่นไปเท่าไร?'},story:{division:'รหัสลับมี 2,880 หน่วย แบ่งกุญแจละ 24 หน่วย ต้องใช้กี่กุญแจ?',fraction:'แผนที่เปิดแล้ว 3/4 ส่วน แต่เบาะแสอยู่ใน 1/3 ของส่วนที่เปิด จะเป็นเท่าไร?'}};return(map[pick]&&map[pick][topic.id])||`ภารกิจวันนี้: ใช้แนวคิด “${topic.title}” แก้ปัญหาหนึ่งข้อให้สำเร็จ`;}
function strategyText(t,strategy){if(strategy==='prediction')return`ก่อนครูบอกวิธี ลองเดาก่อนว่าโจทย์นี้ควรใช้ “คูณ / หาร / เปรียบเทียบ / แบ่งเป็นส่วน” แบบไหน การเดาก่อนช่วยให้สมองสร้างที่วางสำหรับความรู้ใหม่`;if(strategy==='analogy')return interestScenario(t);if(strategy==='visual')return`มองโครงสร้างก่อนตัวเลข: ${t.visual}`;if(strategy==='prereq')return`เราจะถอยหนึ่งขั้นก่อน ไม่ฝืนทำข้อยาก: ${t.alt}`;if(strategy==='teachback')return`รอบนี้ครูจะอธิบายสั้นมาก แล้วให้เราลองสอนครูกลับว่า “ทำไมวิธีนี้ถึงใช้ได้”`;return t.lesson;}
function tutor(id,forceStrategy){const t=findTopic(id),st=topicState(id),strategy=forceStrategy||chooseStrategy(id);lastStrategy=strategy;lessonStartedAt=Date.now();updateTopic(id,{seen:(st.seen||0)+1,learn:(st.learn||0)+1});event('tutor_action',{topic:id,strategy});show('work');$('pane').innerHTML=`<button class="back" onclick="KLH.renderTopics()">← เลือกเรื่องอื่น</button><div class="mission"><small>ภารกิจวันนี้ • ${esc(SUBJECTS[subject].name)}</small><h1>${esc(t.title)}</h1><p>${esc(interestScenario(t))}</p></div><div class="ai-stage"><div class="ai-face">🧠</div><div class="bubble"><small>ครู AI • วิธีสอนรอบนี้: ${esc(strategyLabel(strategy))}</small><h2>ลองมองแบบนี้</h2><p>${esc(strategyText(t,strategy))}</p><div class="visual">${esc(t.visual)}</div><div class="policy">ครูไม่ได้ล็อกว่าเราต้องเรียนแบบนี้ตลอด ระบบกำลังทดลองว่า “วิธีไหนช่วยให้ทำโจทย์ใหม่ได้จริง” แล้วจะเปลี่ยนตามหลักฐาน</div></div></div><div class="quick"><button class="btn light" onclick="KLH.alt('${id}')">อธิบายอีกแบบ</button><button class="btn light" onclick="KLH.visual('${id}')">ขอเห็นภาพก่อน</button><button class="btn light" onclick="KLH.predict('${id}')">ให้ฉันเดาก่อน</button><button class="btn primary" onclick="KLH.tryOne('${id}')">เข้าใจแล้ว ลอง 1 ข้อ</button></div>${twinDetail(id)}`;}
function strategyLabel(s){return{direct:'อธิบายตรงๆ',analogy:'โยงกับสิ่งที่ชอบ',visual:'เห็นภาพก่อน',prediction:'เดาก่อนเฉลย',teachback:'สอน AI กลับ',prereq:'ถอยหนึ่งขั้น'}[s]||s;}
function alt(id){const st=topicState(id);updateTopic(id,{alt:(st.alt||0)+1});incSignal('altExplain');scoreStrategy(lastStrategy,-.15);event('request_alt',{topic:id,from:lastStrategy});tutor(id,lastStrategy==='analogy'?'visual':'analogy');}
function visual(id){event('request_visual',{topic:id});scoreStrategy('visual',.15);tutor(id,'visual');}
function predict(id){event('request_prediction',{topic:id});scoreStrategy('prediction',.1);tutor(id,'prediction');}
function tryOne(id){event('lesson_to_try',{topic:id,seconds:Math.round((Date.now()-lessonStartedAt)/1000),strategy:lastStrategy});practice(id,'learn-check');}
function practice(id,kind){const t=findTopic(id),st=topicState(id);updateTopic(id,{practice:(st.practice||0)+1});event('practice_start',{topic:id,kind,strategy:lastStrategy});show('work');$('pane').innerHTML=`<button class="back" onclick="KLH.renderTopics()">← กลับ</button><div class="qbox"><div class="qlead">${kind==='exam'?'ลองข้อสอบ':'ลองใช้ความเข้าใจ'} • ${esc(t.title)}</div><h2>${esc(t.q.p)}</h2><div class="choices">${t.q.c.map((c,i)=>`<button class="choice" onclick="KLH.answer('${id}',${i},'${kind}')">${String.fromCharCode(65+i)}. ${esc(c)}</button>`).join('')}</div><div id="feedback"></div></div>${twinDetail(id)}`;}
function answer(id,i,kind){const t=findTopic(id),ok=i===t.q.a,st=topicState(id);document.querySelectorAll('.choice').forEach(b=>b.disabled=true);if(ok){updateTopic(id,{correct:(st.correct||0)+1});incSignal('correct');if((st.practice||0)<=1)incSignal('firstTryCorrect');scoreStrategy(lastStrategy,.3);event('answer',{topic:id,correct:true,kind,strategy:lastStrategy});$('feedback').innerHTML=`<div class="feedback ok"><strong>ถูกต้อง 🎯</strong><br>สิ่งสำคัญไม่ใช่แค่ตอบถูก แต่คือวิธีที่เราใช้ยังทำงานกับโจทย์ใหม่ได้</div><div class="quick"><button class="btn primary" onclick="KLH.teachBack('${id}')">ลองสอน AI กลับ</button><button class="btn light" onclick="KLH.renderTopics()">เลือกเรื่องต่อไป</button></div>`;}else{updateTopic(id,{wrong:(st.wrong||0)+1});incSignal('wrong');scoreStrategy(lastStrategy,-.2);scoreStrategy('prereq',.12);event('answer',{topic:id,correct:false,kind,strategy:lastStrategy});$('feedback').innerHTML=`<div class="feedback retry"><strong>ยังไม่ใช่ — ดีที่รู้ตอนนี้</strong><br>ครูจะไม่ยิงโจทย์ซ้ำแบบเดิม เราจะเปลี่ยนวิธีอธิบายแล้วค่อยลองใหม่</div><div class="quick"><button class="btn primary" onclick="KLH.tutor('${id}','prereq')">ครูเปลี่ยนวิธีให้</button><button class="btn light" onclick="KLH.tutor('${id}','visual')">ขอเห็นภาพ</button></div>`;}}
function teachBack(id){const t=findTopic(id);scoreStrategy('teachback',.12);event('teachback_prompt',{topic:id});$('pane').innerHTML=`<button class="back" onclick="KLH.renderTopics()">← กลับ</button><div class="mission"><small>Boss Move</small><h1>คราวนี้ ${esc(ctx().name)} เป็นครู</h1><p>ถ้าอธิบายได้ด้วยภาษาของตัวเอง แปลว่าเราไม่ได้แค่จำคำตอบ</p></div><div class="ai-stage"><div class="ai-face">🤖</div><div class="bubble"><small>AI นักเรียน</small><h2>ช่วยสอนฉันหน่อย</h2><p>ถ้าฉันเจอโจทย์ “${esc(t.title)}” ฉันควรเริ่มคิดจากอะไร? พูดกับพ่อแม่หรืออธิบายออกเสียงให้ตัวเองฟังก็ได้ แล้วกดว่าทำได้หรือยังติดอยู่</p></div></div><div class="decision-actions"><button class="yes" onclick="KLH.teachBackDone('${id}',true)">อธิบายได้เอง</button><button class="no" onclick="KLH.teachBackDone('${id}',false)">ยังติดนิดหนึ่ง</button></div>`;}
function teachBackDone(id,ok){event('teachback_selfreport',{topic:id,ok});if(ok)scoreStrategy('teachback',.25);else scoreStrategy('visual',.1);$('pane').innerHTML=`<div class="decision"><div class="big">${ok?'🌟':'🧩'}</div><h1>${ok?'เยี่ยม นี่คือความเข้าใจที่ใช้ต่อได้':'เจอจุดที่ยังต้องคลาย'}</h1><p class="question">${ok?'ต่อไปครูจะกลับมาลองโจทย์ใหม่อีกครั้งในวันหลัง เพื่อดูว่ายังทำได้อยู่ไหม':'ครูจะจำไว้ว่ารอบนี้การอธิบายกลับยังยาก แล้วเปลี่ยนวิธีในครั้งต่อไป'}</p><div class="quick" style="justify-content:center"><button class="btn primary" onclick="KLH.home()">กลับหน้าหลัก</button></div></div>`;}
function twinDetail(id){const s=topicState(id);return`<details class="twin"><summary>Learner Twin • DEV evidence</summary><div class="twin-grid"><div class="mini"><span>รอบเรียน</span><strong>${s.learn||0}</strong></div><div class="mini"><span>ถูก / ผิด</span><strong>${s.correct||0} / ${s.wrong||0}</strong></div><div class="mini"><span>สถานะเนื้อหา</span><strong>${esc(s.exposure||'UNKNOWN')}</strong></div></div></details>`;}

window.KLH={start,home,toggleInterest,openSubject,openMode,renderTopics,chooseTopic,learned,notYet,learnFuture,tutor,alt,visual,predict,tryOne,answer,teachBack,teachBackDone};
$('school').addEventListener('change',syncFields);$('schoolOther').addEventListener('input',schoolInfo);$('goal').addEventListener('change',syncFields);$('targetSchool').addEventListener('change',syncFields);
renderInterests();loadSchools();const existing=ctx();if(existing){const t=twin();t.signals.returns=(t.signals.returns||0)+1;saveTwin(t);}
})();